run_name: energy_model_CFD_v
dtype: float32

# Data
hdf5_file: /project/biocomplexity/fa7sa/calochallenge_datasets/dataset_2/dataset_2_1.hdf5
eval_hdf5_file: /project/biocomplexity/fa7sa/calochallenge_datasets/dataset_2/dataset_2_2.hdf5
xml_filename: /project/biocomplexity/fa7sa/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.001
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"

# Preprocessing
transforms:
    #ScaleVoxels:
    #    factor: 0.35
    NormalizeByElayer:
        ptype: /project/biocomplexity/fa7sa/calo_dreamer/src/challenge_files/binning_dataset_2.xml
        xml_file: electron
    ScaleTotalEnergy: 
        factor: 0.35
    SelectDims:
        start: -45
        end: 0
    ExclusiveLogitTransform:
        delta: 1.0e-6
        rescale: True
    StandardizeFromFile: {}
    LogEnergy: {}
    ScaleEnergy:
        e_min: 6.907755
        e_max: 13.815510
    Reshape:
        shape: [45, 1]
e_min: 6.907755
e_max: 13.815510
# Model
model_type: energy
gen_model: 'DDPM'
model: TransfusionDDPM
network: ARtransformerModified
shape: [45] # number of calorimeter layers
dim_embedding: 64
n_head: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 512
num_timesteps: 1000
#encode_c_dim: 64
n_con: 1
conditional: True
# c_embed and x_embed was false
c_embed: True
x_embed: True
#conditional: True
#encode_t: True
#encode_t_dim: 64
#encode_c: True
normalization: LayerNorm
cross_attention: True
residual: False
prediction_type: epsilon  #epsilon, x and v
# Training
lr: 1.e-3 # was 1e-3
max_lr: 2.e-3
batch_size: 1024
validate_every: 5
use_scheduler: True
lr_scheduler: one_cycle_lr
# weight_decay: 0.001
betas: [0.9, 0.999]
n_epochs: 400 #WAS 500
cycle_epochs: 500
save_interval: 100_001
sample_periodically: False
sample_every: 10
sample_every_n_samples: 1001
beta_schedule: linear #sigmoid  #cosine #linear
# Evaluation
eval_mode: all
n_samples: 10000
batch_size_sample: 1000
sample_us: True
# solver_kwargs:
#     # method: dopri5
#     # atol: 1.e-4
#     # rtol: 1.e-6
#     method: rk4
#     options:
#         step_size: 0.02
        
LBL: DDPM
use_cfd: True
lambda_cfd: 0.1     # start small
alpha_logit: 1.0e-6    # your ExclusiveLogitTransform delta
cfd_warmup_steps: 3000
base_corr: '/project/biocomplexity/fa7sa/Modified_Training_Objective/LANTERN_new/C_real_global.npy'
stats_ds2: '/project/biocomplexity/fa7sa/Modified_Training_Objective/LANTERN_new/stats_ds2'

# NEW
cfd_ema_beta: 0.90             # EMA ON
cfd_shrink_alpha: 0.05         # shrink ON
cfd_shrink_target: identity